root = "."
tmp_dir = ".tmp"

[build]
pre_cmd = []
cmd = "task build -- -gcflags=all='-N -l'"
post_cmd = []
full_bin = "dlv"
args_bin = [
  "exec",
  "--listen=:2345",
  "--headless=true",
  "--api-version=2",
  "--accept-multiclient",
  "--continue",
  "./dist/external-dns-webhook-opnsense",
  "--",
]
include_ext = ["go"]
exclude_dir = [".task", "dist", "bin", "vendor"]
include_dir = []
include_file = []
exclude_file = []
exclude_regex = ["_test\\.go"]
exclude_unchanged = true
follow_symlink = true
poll = false
poll_interval = 500
delay = 0
stop_on_error = true
send_interrupt = true
kill_delay = 500
rerun = false
rerun_delay = 500

[log]
time = false
main_only = true

[misc]
clean_on_exit = true

[screen]
clear_on_rebuild = false
keep_scroll = true

[proxy]
enabled = true
