---
name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

env:
  GO_VERSION: "1.25"

jobs:
  checks:
    name: run checks
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: checkout code
        uses: actions/checkout@v6

      - name: set up go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: install dependencies
        run: go mod vendor

      - name: generate mocks
        run: mockery

      - name: run lint
        run: golangci-lint run

      - name: run tests
        run: go tool ginkgo --cover --coverpkg=./... --coverprofile=coverage.out -vv --silence-skips --fail-fast -r ./...

      - name: build
        run: go build -mod=vendor -o ./dist/external-dns-webhook-opnsense .
